### ISSUE TITLE
List of values as ranks no longer supported?

### ISSUE THREAD

**Issue by AtomicCactus** [rballester/tntorch#41]
Hey there, love the library! I noticed that in the documentation it shows us being able to pass in a `List` or other `Sequential` into `ranks_cp` and other `ranks_` arguments. However, currently I'm not really able to do that. 

The following works fine:
```python
# Full is a 2D tensor [32,32]
t = tn.Tensor(full, ranks_cp=16)
```

But the following throws an exception:
```python
# Full is a 2D tensor [32,32]
t = tn.Tensor(full, ranks_cp=[8, 8])
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yuri/.local/lib/python3.10/site-packages/tntorch/tensor.py", line 151, in __init__
    assert not hasattr(ranks_cp, '__len__')
AssertionError
```

Is this functionality no longer supported? I'm seeing it both in the code comments as well as official documentation, so at least wanted to call out as an inconsistency.

**Comment by rballester** [comment]
Thanks for your interest in tntorch and for spotting this inconsistency. Passing a list of CP ranks was never supported (unlike lists of Tucker or TT ranks, which are supported). I've updated the docs to reflect this (3af563a).
